fix: redirect hubs.mozilla.com to sumo article
mozilla-it/refractr pull request #324
Opened 2024-05-30 19:00 UTC by pattersonbl2

## Refractr PR Checklist

JIRA ticket: https://mozilla-hub.atlassian.net/browse/SVCSE-1946

When creating a PR for Refractr, confirm you've done the following steps for smooth CI and CD experiences:
- [* ] Have you updated the relevant YAML in the PR?
- [* ] Have you checked the relevant YAML for any possible dupes regarding your domain?
- [ *] Have you checked if there are any TLS cert concerns - e.g. if the domain being redirected already exists, and it is being changed to point at Refractr, is a temporary TLS 'outage' while waiting for Lets Encrypt certification via HTTP challenge okay? If not, [have you followed these steps for using DNS challenges with our cert-manager setup](https://mana.mozilla.org/wiki/display/SRE/Refractr+-+How+To+-+DNS+Challenges)?
- [ ] If desired, have you generated the Nginx manually to confirm addition works as expected? 
- [ ] If desired, are you able to connect to EKS (cluster itse-apps-prod-1, namespace fluxcd) to more closely monitor the deploys?

After PR merge, next steps include:
- [ ] If going straight from main merge & Stage deploy to a release & production deploy, create the relevant GitHub release with an incremented version / tag applied.
- [ ] Confirm you are ready and able to perform the requested DNS creation or change post-deploy?

2024-05-30 19:03 UTC, pattersonbl2 commented
For context,  The hubs service in GCP will be shutdown and the project deleted.   I am not sure if this changes the process.

2024-05-30 19:17 UTC, gcoxmoz commented
Note that there are other hubs URLs in the refractr config that you may want to consolidate/clean as a part of this winddown.  I don't /think/ this is a blocker, but pointing it out while it's fresh.

2024-05-30 19:49 UTC, bkochendorfer requested changes

2024-05-30 19:49 UTC, bkochendorfer commented on prod-refractr.yml
> +    - hubs.mozilla.com/labs/
I think you can remove the path here if you are redirecting the entire domain it would never get hit

```suggestion
```

2024-05-30 20:44 UTC, pattersonbl2 commented
@gcoxmoz @bkochendorfer  I have pushed a change to clean up the redirect url's and removed the  /lab url.

2024-05-30 20:59 UTC, gcoxmoz commented
I have no review power here, but conceptual f+

2024-05-30 21:41 UTC, bkochendorfer approved these changes
LGTM, let me know when you want to us to deploy.

2024-05-31 12:20 UTC, pattersonbl2 commented
@bkochendorfer  They are planning to start the shutdown around 11am est time.  I want to give time for the main gke cluster to be shutdown so i am thinking 1 pm est.

2024-05-31 16:22 UTC, merged