observatory-stage-move
mozilla-it/refractr pull request #359
Opened 2024-10-02 11:42 UTC by argl

## Refractr PR Checklist

JIRA ticket: [link to relevant JIRA or other system ticket]

When creating a PR for Refractr, confirm you've done the following steps for smooth CI and CD experiences:
- [x] Have you updated the relevant YAML in the PR?
- [x] Have you checked the relevant YAML for any possible dupes regarding your domain?
- [x] Have you checked if there are any TLS cert concerns - e.g. if the domain being redirected already exists, and it is being changed to point at Refractr, is a temporary TLS 'outage' while waiting for Lets Encrypt certification via HTTP challenge okay? If not, [have you followed these steps for using DNS challenges with our cert-manager setup](https://mana.mozilla.org/wiki/display/SRE/Refractr+-+How+To+-+DNS+Challenges)?
- [ ] If desired, have you generated the Nginx manually to confirm addition works as expected? 
- [ ] If desired, are you able to connect to EKS (cluster itse-apps-prod-1, namespace fluxcd) to more closely monitor the deploys?

After PR merge, next steps include:
- [ ] If going straight from main merge & Stage deploy to a release & production deploy, create the relevant GitHub release with an incremented version / tag applied.
- [ ] Confirm you are ready and able to perform the requested DNS creation or change post-deploy?

2024-10-07 09:37 UTC, caugner requested changes
LGTM, but let's use HTTP 301.

PS: You might also want to link the Jira bug in the PR description directly.

2024-10-07 09:37 UTC, caugner commented on prod-refractr.yml
> +  status: 302
Note that we'll want HTTP 301 to get the SEO authority.

2024-10-07 09:40 UTC, caugner commented
`chore: redirect observatory.allizom.org to developer.allizom.org/en-US/observatory`

2024-10-07 13:31 UTC, caugner commented on prod-refractr.yml
> +    - http://observatory.allizom.org/: https://developer.allizom.org/en-US/observatory/
Oh, interesting, do the tests not run on PRs?

2024-10-07 13:51 UTC, argl commented on prod-refractr.yml
> +    - http://observatory.allizom.org/: https://developer.allizom.org/en-US/observatory/
Fixed. Please review again

2024-10-07 14:14 UTC, ahoneiser approved these changes
lgtm

2024-10-07 17:46 UTC, ahoneiser commented
We've just created a new release for refractr ([v0.0.191](https://github.com/mozilla-it/refractr/releases/tag/v0.0.191)), PR needs a rebase :slightly_smiling_face:

2024-10-08 08:24 UTC, argl commented
Should be up to date now.

2024-10-08 14:18 UTC, merged